repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                _layouts/.*|
                _includes/.*|
                assets/.*
            )$
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                _layouts/.*|
                _includes/.*|
                assets/.*
            )$
    -   id: check-case-conflict
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.35.0
  hooks:
  - id: markdownlint
